sudo: required

language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"

services:
  - docker

before_install:
  - git clone https://github.com/docsbox/docsbox.git && cd docsbox
  - docker-compose build
  - docker-compose up -d

script:
  - nosetests
